### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by JoanValiente** [AngryFrogDev/Dungeon-Brawler#38] opened 2018-05-07 11:16 UTC
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
B

---
### What is the expected behaviour?
Be able to defend or dodge some attacks.

---
### What is the actual behaviour shown?
Some attacks can be spamed and the other player can't do nothing. (fireball)

---

**Comment by t3m1X** [comment] 2018-05-15 10:05
Duplicate of #36

**Closed as completed by t3m1X** 2018-05-15 10:05 UTC
Labels: duplicate
