### ISSUE TITLE
mage stops working

### ISSUE THREAD

**Issue by morgadoCV** [AngryFrogDev/Dungeon-Brawler#62] opened 2018-05-07 11:28 UTC
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_

B

---
### What is the expected behaviour?
Mage should move

---
### What is the actual behaviour shown?
Once you press RB+some arrow, mage stops working. if he gets hit, he goes back to normal but keeps not working 
 can't screenshot it because the game was played on another pc
---
### Indicate us the steps to reproduce said behaviour:
keep rb and right button down, instad of charging the spell it will stop, (happened to me in 2 of 4 games)

**Comment by t3m1X** [comment] 2018-05-15 10:28
Duplicate of #52

**Closed as completed by t3m1X** 2018-05-15 10:28 UTC
Labels: duplicate
