### ISSUE TITLE
I don't know why but the rogue gets stuck in atk animation

### ISSUE THREAD

**Issue by ninalb13** [AngryFrogDev/Dungeon-Brawler#68] opened 2018-05-08 08:55 UTC
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_

---
### What is the expected behaviour?

---
### What is the actual behaviour shown?

---

**Comment by t3m1X** [comment] 2018-05-15 10:16
Duplicate of #37

**Closed as completed by t3m1X** 2018-05-15 10:17 UTC
Labels: duplicate
