### ISSUE TITLE
Players animations on rematch menu

### ISSUE THREAD

**Issue by JoanValiente** [AngryFrogDev/Dungeon-Brawler#43] opened 2018-05-07 11:17 UTC
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
C

---
### What is the expected behaviour?
Normal animation.

---
### What is the actual behaviour shown?
The animation gets buged when the game ends. (On the rematch menu).

---

**Comment by t3m1X** [comment] 2018-05-15 10:25
Duplicate of #37

**Closed as completed by t3m1X** 2018-05-15 10:25 UTC
Labels: duplicate
