### ISSUE TITLE
Loop in Attack Anim

### ISSUE THREAD

**Issue by AitorSimona** [AngryFrogDev/Dungeon-Brawler#86] opened 2018-05-15 07:00 UTC
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
C

---
### What is the expected behaviour?
The player stops the attack animation when killing the other player

---
### What is the actual behaviour shown?
The attack animation keeps playing, entering a loop.

---
### Indicate us the steps to reproduce said behaviour:
Choose Moriah (LeatherCloack)and kill the other player (in this case D'Raven with wizard hat) with LB attack

**Comment by t3m1X** [comment] 2018-05-15 10:15
Duplicate of #37

**Closed as completed by t3m1X** 2018-05-15 10:15 UTC
Labels: duplicate
