### ISSUE TITLE
Mage easy win when spam Fireball at the beggining of the game

### ISSUE THREAD

**Issue by lFreecss** [AngryFrogDev/Dungeon-Brawler#53] opened 2018-05-07 11:22 UTC
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
B - Important, Gameplay Affected

---
### What is the expected behaviour?
The warrior can take the oportunity to attack the mage

---
### What is the actual behaviour shown?
Spamming Fireball it's a easy win to the mage

---
### Indicate us the steps to reproduce said behaviour:
Start the game, spam fireball.

**Comment by t3m1X** [comment] 2018-05-15 10:18
Duplicate of #36

**Closed as completed by t3m1X** 2018-05-15 10:18 UTC
Labels: duplicate
